pipeline {
	agent any
	tools {nodejs "MyNode"}		
	stages {
		stage("Check Node Version"){
			steps {
			sh "node --version"
			}
		}
		stage("Install Dependencies"){
			steps {
			sh "npm --version"
			sh "npm install"
			}
		}
		stage("Test"){
			steps {
			sh "node nodeWithJenkins/app.js"
		}
		}
		stage("Release the version"){
			steps {
			echo "Release the Version"
			}
		}
	}
}
